spring.application.name=jwt-auth-mark-1

spring.datasource.username=springstudent
spring.datasource.password=springstudent
spring.datasource.url=jdbc:mysql://localhost:3308/product_users_database


spring.security.